name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests
        run: pytest ./test_app.py

      - name: Clean up workspace
        if: always()
        run: |
          rm -rf __pycache__
          rm -rf .pytest_cache